A cython / python implementation of the [[https://www.pik-potsdam.de/copan][COPAN]] Exploit model.

* Model Descriptions
The Exploit model is an agent based model, conceptualizing planetary social-ecological coevolution. Each of the =N= agents harvests its individual resource according to either a sustainble or non-sustainble strategy reflecting either long-term sustainable yields or short-term profit maximization. These strategies get updated via a preference formation process covering two key schemes of social interaction: imitation and homophily.

* Implementation
- [[file:cyexploit/exploit_core.pyx][exploit_core.py]] : The basic model is implemented in the [[http://cython.org/][cython]] language, combining easy python and fast c.
- [[file:cyexploit/exploit_explore.py][exploit_explore]] : This derived class (shall) collect methods to explore the Exploit model interactively

* Unittests
We are using the python testing framework [[http://pytest.org/latest/][pytest]] with [[https://pypi.python.org/pypi/pytest-pep8][pep8]] style guide and [[https://pypi.python.org/pypi/pytest-flakes][pyflakes]] error checking.
Please write corresponding unittests while developing and make sure that all test pass by executing

: py.test

in the root of the project tree.


* Related Publications

- Wiedermann, M, Donges, JF, Heitzig, J, Lucht, W, and Kurths, J (2015),
  *Macroscopic description of complex adaptive networks co-evolving with dynamic node states*,
  Physical Review E 91, 052801,
  DOI: [[http://dx.doi.org/10.1103/PhysRevE.91.052801][10.1103/PhysRevE.91.052801]],
  Preprint: [[http://arxiv.org/abs/1503.05914][arxiv:1503.05914]] [physics.soc-ph].
* License
=cyexploit= is [[file:LICENSE.txt][BSD-licensed]] (3 clause)
